{
 "title": "DPI",
 "tags": [ "DPI" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "query_result(max by (nodename) (  max_over_time(tuxedovpn_dpi_uptime_seconds{job=\"dpi_agent_vpn\"}[15m])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "DPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DPI Last Event ${nodename}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuxedovpn_dpi_last_event_timestamp_seconds{nodename=~\"$nodename\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DPI Uptime ${nodename}",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuxedovpn_dpi_uptime_seconds{nodename=~\"$nodename\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "tuxedovpn_dpi_events_total $nodename",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "label_join(\r\n  max by (nodename, user, reason) (\r\n    max_over_time(\r\n      (increase(tuxedovpn_dpi_events_total{stage=\"detect\", result=\"match\", nodename=~\"$nodename\"}[5m]) > bool 0)[30m:1m]\r\n    )\r\n  ),\r\n  \"join_key\", \"|\", \"nodename\", \"user\", \"reason\"\r\n)\r\n",
     "legendFormat": "match_detect"
    },
    {
     "expr": "label_join(\r\n  max by (nodename, user, reason) (\r\n    max_over_time(\r\n      (increase(tuxedovpn_dpi_events_total{stage=\"disconnect\",result=\"success\", nodename=~\"$nodename\"}[5m]) > bool 0)[30m:1m]\r\n    )\r\n  ),\r\n  \"join_key\", \"|\", \"nodename\", \"user\", \"reason\"\r\n)",
     "legendFormat": "success_disconnect"
    },
    {
     "expr": "label_join(\r\n  max by (nodename, user, reason) (\r\n    max_over_time(\r\n      (increase(tuxedovpn_dpi_events_total{stage=\"webhook\", result=\"success\", nodename=~\"$nodename\"}[5m]) > bool 0)[30m:1m]\r\n    )\r\n  ),\r\n  \"join_key\", \"|\", \"nodename\", \"user\", \"reason\"\r\n)\r\n",
     "legendFormat": "success_webhook"
    }
   ]
  }
 ]
}