{
 "title": "FreeRadius Accounting",
 "tags": [ "FreeRadius" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(tuxedovpn_radacct_total_octets_total,job)"
    }
   },
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "label_values(tuxedovpn_radacct_user_total_octets_total{job=\"$job\"}, user)"
    }
   },
   {
    "name": "nas",
    "label": "Nas",
    "query": {
     "query": "label_values(tuxedovpn_radacct_user_total_octets_by_nas_total{job=\"$job\",nas!=\"\"}, nas)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exporter health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(tuxedovpn_freeradius_accounting_exporter_scrape_success{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users right now",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by (user) (\r\n  tuxedovpn_radacct_user_active_sessions{job=\"$job\"}\r\n)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Users last seen",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "tuxedovpn_radacct_user_last_seen_timestamp_seconds{job=\"$job\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuxedovpn_radacct_active_sessions{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total for selected range",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user) (increase(tuxedovpn_radacct_user_total_octets_total{job=\"$job\"}[$__range])) / 1024 / 1024 / 1024",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Download for selected range",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user) (increase(tuxedovpn_radacct_user_output_octets_total{job=\"$job\"}[$__range])) / 1024 / 1024 / 1024",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Upload for selected range",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user) (increase(tuxedovpn_radacct_user_input_octets_total{job=\"$job\"}[$__range])) / 1024 / 1024 / 1024",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Top users by current throughput",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, 8 * rate(tuxedovpn_radacct_user_total_octets_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "Connection speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total download/upload",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(tuxedovpn_radacct_input_octets_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Upload"
    },
    {
     "expr": "8 * rate(tuxedovpn_radacct_output_octets_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Total throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(tuxedovpn_radacct_total_octets_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Per-user throughput - $user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(tuxedovpn_radacct_user_total_octets_total{job=\"$job\",user=\"$user\"}[$__rate_interval])",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}