{
 "title": "FreeRadius Accounting",
 "tags": [ "FreeRadius" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(tuxedovpn_radacct_total_octets_total,job)"
    }
   },
   { "name": "acct_interval", "label": "Acct interval", "query": "${VAR_ACCT_INTERVAL}" },
   { "name": "acct_interval_s", "label": "Acct interval (s)", "query": "${VAR_ACCT_INTERVAL_S}" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exporter health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(tuxedovpn_freeradius_accounting_exporter_scrape_success{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users last seen",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "tuxedovpn_radacct_user_last_seen_timestamp_seconds{job=\"$job\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuxedovpn_radacct_active_sessions{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total for selected range",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum by (user) (clamp_min(delta(tuxedovpn_radacct_user_total_octets_total{job=\"$job\"}[$__range]), 0))\r\n) / 1024 / 1024 / 1024",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Active users right now",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (user) (\r\n  tuxedovpn_radacct_user_active_sessions{job=\"$job\"}\r\n)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Download for selected range",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum by (user) (clamp_min(delta(tuxedovpn_radacct_user_output_octets_total{job=\"$job\"}[$__range]), 0))\r\n) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Upload for selected range",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum by (user) (clamp_min(delta(tuxedovpn_radacct_user_input_octets_total{job=\"$job\"}[$__range]), 0))\r\n) / 1024 / 1024 / 1024",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Top users by current throughput",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, 8 * rate(tuxedovpn_radacct_user_total_octets_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "Connection speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Total download/upload",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * increase(tuxedovpn_radacct_input_octets_total{job=\"$job\"}[$acct_interval]) / $acct_interval_s",
     "legendFormat": "Upload"
    },
    {
     "expr": "8 * increase(tuxedovpn_radacct_output_octets_total{job=\"$job\"}[$acct_interval]) / $acct_interval_s",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Total throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * increase(tuxedovpn_radacct_total_octets_total{job=\"$job\"}[$acct_interval]) / $acct_interval_s",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}