{
 "title": "OCServ",
 "tags": [ "OCServ" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ocserv_job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\"ocserv_exporter_.*\"}, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(ocserv_scrape_timestamp{job=\"$ocserv_job\"}, nodename)"
    }
   },
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "label_values(ocserv_sessions_bytes_received{job=\"$ocserv_job\",nodename=~\"$nodename\"}, user)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total download/upload throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(ocserv_sessions_bytes_received_total{job=\"ocserv_exporter_vpn\"}[$__rate_interval])",
     "legendFormat": "Download "
    },
    {
     "expr": "8 * rate(ocserv_sessions_bytes_sent_total{job=\"ocserv_exporter_vpn\"}[$__rate_interval])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Top users by current throughput",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, 8 * rate(ocserv_sessions_bytes_received{job=\"ocserv_exporter_vpn\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "topk(10, 8 * rate(ocserv_sessions_bytes_sent{job=\"ocserv_exporter_vpn\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ocserv_sessions_total{job=\"ocserv_exporter_vpn\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}