{
 "title": "OCServ",
 "tags": [ "OCServ" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ocserv_job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\"ocserv_exporter_.*\"}, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "query_result(max by (nodename) (max_over_time(ocserv_scrape_timestamp{job=\"$ocserv_job\"}[15m])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sessions by node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (ocserv_sessions_total{job=\"$ocserv_job\",nodename=~\"$nodename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions $nodename",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "ocserv_sessions_total{job=\"$ocserv_job\",nodename=~\"$nodename\"}",
     "legendFormat": "session"
    }
   ]
  },
  {
   "title": "Total download/upload throughput $nodename",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(ocserv_sessions_bytes_sent_total{job=\"$ocserv_job\",nodename=~\"$nodename\"}[$__rate_interval])",
     "legendFormat": "Download {{nodename}}"
    },
    {
     "expr": "8 * rate(ocserv_sessions_bytes_received_total{job=\"$ocserv_job\",nodename=~\"$nodename\"}[$__rate_interval])",
     "legendFormat": "Upload {{nodename}}"
    }
   ]
  },
  {
   "title": "Top users by current throughput $nodename",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (user) (8 * rate(ocserv_sessions_bytes_received{job=\"$ocserv_job\",nodename=~\"$nodename\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (user) (8 * rate(ocserv_sessions_bytes_sent{job=\"$ocserv_job\",nodename=~\"$nodename\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}