{
 "title": "VPN Clients",
 "tags": [
  "VPN",
  "Clients"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "RADIUS job",
    "query": {
     "query": "label_values(tuxedovpn_radacct_total_octets_total,job)"
    }
   },
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "label_values(tuxedovpn_radacct_user_total_octets_total{job=\"$job\"},user)"
    }
   },
   {
    "name": "ocserv_job",
    "label": "OCServ job",
    "query": {
     "query": "label_values(up{job=~\"ocserv_exporter_.*\"}, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "query_result(max by (nodename) (max_over_time(ocserv_scrape_timestamp{job=\"$ocserv_job\"}[15m])))"
    }
   },
   { "name": "acct_interval", "label": "Acct interval", "query": "${VAR_ACCT_INTERVAL}" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OCServ sessions by node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (ocserv_sessions_total{job=\"$ocserv_job\",nodename=~\"$nodename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RADIUS active sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuxedovpn_radacct_active_sessions{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OCServ connects (selected range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ocserv_sessions_connects_total{job=\"$ocserv_job\",nodename=~\"$nodename\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OCServ disconnects (selected range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ocserv_sessions_disconnects_total{job=\"$ocserv_job\",nodename=~\"$nodename\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accounting exporter health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(tuxedovpn_freeradius_accounting_exporter_scrape_success{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OCServ total download/upload throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (nodename) (8 * rate(ocserv_sessions_bytes_sent{job=\"$ocserv_job\",nodename=~\"$nodename\"}[$__rate_interval])) or sum by (nodename) (0 * ocserv_sessions_total{job=\"$ocserv_job\",nodename=~\"$nodename\"})",
     "legendFormat": "Download {{nodename}}"
    },
    {
     "expr": "sum by (nodename) (8 * rate(ocserv_sessions_bytes_received{job=\"$ocserv_job\",nodename=~\"$nodename\"}[$__rate_interval])) or sum by (nodename) (0 * ocserv_sessions_total{job=\"$ocserv_job\",nodename=~\"$nodename\"})",
     "legendFormat": "Upload {{nodename}}"
    }
   ]
  },
  {
   "title": "RADIUS accounting total download/upload (smoothed, per NAS→nodename)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (nodename) (8 * rate(tuxedovpn_radacct_input_octets_by_nas_total{job=\"$job\",nodename=~\"$nodename\"}[$acct_interval]))",
     "legendFormat": "Upload {{nodename}}"
    },
    {
     "expr": "sum by (nodename) (8 * rate(tuxedovpn_radacct_output_octets_by_nas_total{job=\"$job\",nodename=~\"$nodename\"}[$acct_interval]))",
     "legendFormat": "Download {{nodename}}"
    }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Top users by current throughput (OCServ) $nodename",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (user) (8 * rate(ocserv_sessions_bytes_received{job=\"$ocserv_job\",nodename=~\"$nodename\",user=~\"$user\",user!~\"^$|^[(]none[)]$\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (user) (8 * rate(ocserv_sessions_bytes_sent{job=\"$ocserv_job\",nodename=~\"$nodename\",user=~\"$user\",user!~\"^$|^[(]none[)]$\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top users by disconnects (OCServ) $nodename",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, round(sum by (user) (increase(ocserv_session_disconnects_total{job=\"$ocserv_job\",nodename=~\"$nodename\",user=~\"$user\",user!~\"^$|^[(]none[)]$\"}[$__range]))))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Traffic for selected range (RADIUS) $user",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (user) (clamp_min(delta(tuxedovpn_radacct_user_total_octets_total{job=\"$job\",user=~\"$user\"}[$__range]), 0))) / 1024 / 1024 / 1024",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Users last seen (RADIUS) $user",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "tuxedovpn_radacct_user_last_seen_timestamp_seconds{job=\"$job\",user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "Selected user", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "User throughput (OCServ) $user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (user) (8 * rate(ocserv_sessions_bytes_sent{job=\"$ocserv_job\",nodename=~\"$nodename\",user=~\"$user\",user!~\"^$|^[(]none[)]$\"}[$__rate_interval]))",
     "legendFormat": "Download {{user}}"
    },
    {
     "expr": "sum by (user) (8 * rate(ocserv_sessions_bytes_received{job=\"$ocserv_job\",nodename=~\"$nodename\",user=~\"$user\",user!~\"^$|^[(]none[)]$\"}[$__rate_interval]))",
     "legendFormat": "Upload {{user}}"
    }
   ]
  },
  {
   "title": "User connects/disconnects (events/min, OCServ) $user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "60 * sum by (user) (rate(ocserv_session_connects_total{job=\"$ocserv_job\",nodename=~\"$nodename\",user=~\"$user\",user!~\"^$|^[(]none[)]$\"}[$__rate_interval]))",
     "legendFormat": "Connects/min {{user}}"
    },
    {
     "expr": "60 * sum by (user) (rate(ocserv_session_disconnects_total{job=\"$ocserv_job\",nodename=~\"$nodename\",user=~\"$user\",user!~\"^$|^[(]none[)]$\"}[$__rate_interval]))",
     "legendFormat": "Disconnects/min {{user}}"
    }
   ]
  },
  {
   "title": "Truth check: physical NIC throughput (node_exporter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max by (nodename) (\r\n  8 * rate(node_network_transmit_bytes_total{job=~\"node_.*\",device!~\"^(lo|wg.*|tun.*|tap.*|docker.*|veth.*|br-.*|cni.*)$\"}[$__rate_interval])\r\n  * on(instance) group_left(nodename)\r\n  node_uname_info{job=~\"node_.*\",nodename=~\"$nodename\"}\r\n)",
     "legendFormat": "Download {{nodename}} (NIC)"
    },
    {
     "expr": "max by (nodename) (\r\n  8 * rate(node_network_receive_bytes_total{job=~\"node_.*\",device!~\"^(lo|wg.*|tun.*|tap.*|docker.*|veth.*|br-.*|cni.*)$\"}[$__rate_interval])\r\n  * on(instance) group_left(nodename)\r\n  node_uname_info{job=~\"node_.*\",nodename=~\"$nodename\"}\r\n)",
     "legendFormat": "Upload {{nodename}} (NIC)"
    }
   ]
  }
 ]
}